$(function(){Cycle();flatScroll();archived()});$(document).click(Cycle);var $boardIndex=$(".discussion-list-item").length,$chronoView=0,$subBoard=$("#breadcrumbs h2").text(),firstRun=1,pageURL=window.location.href,region=null,lang=null;
function Cycle(){var b=setInterval(function(){firstRun=1;$chronoView=$("#comments").find(".list").length;var a=pageURL.split("/");region=pageURL.split(".")[1];lang=a[3];++firstRun;0<$boardIndex&&IndexVoting();newTags();commentParent()},750);setTimeout(function(){clearInterval(b)},4500)}
function IndexVoting(){$("#discussion-list").find("td.voting:not(#cv):not(:has(.pin)):contains('                ')").attr("id","cv").html("<div class='locked'></div>").end().find("ul.upVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #009700").end().end().end().find("ul.downVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #e23636").end().end().end().find("button.up-vote").remove().end().find("button.down-vote").remove().end();for(var b=
$("#discussion-list").find(".riot-apollo.voting:not(.wx)"),a=0;a<b.length;++a){var d=b[a];d.className+=" wx";$v=$(d);d=$v.attr("data-apollo-up-votes");var f=$v.attr("data-apollo-down-votes");d-=f;1===d?$v.find("ul.riot-voting").append("<li>Vote</li>").end().find(".total-votes").attr("style","color:#22b722"):0===d?$v.find(".total-votes").attr("style","color:#13bbc1").end().find("ul.riot-voting").append("<li>Votes</li>"):0<d?$v.find(".total-votes").attr("style","color:#22b722").end().find("ul.riot-voting").append("<li>Votes</li>"):
0>d&&$v.find(".total-votes").attr("style","color:#fd3b3b").end().find("ul.riot-voting").append("<li>Votes</li>")}}
function newTags(){z="https://boards."+region+".leagueoflegends.com/api/LMxoEARA/discussions/yyKrU1eL?page_size=0";var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var a=JSON.parse(this.responseText).discussion.content.body_html.split(";"),b=a[1].split(","),f=a[3].split(","),g=a[5].split(","),k=a[7].split(","),e=a[9].split(","),c=a[11].split(",");$("a.profile-hover:not(.cka)").each(function(){$this=$(this);this.className+=" cka";!1===$this.parent().hasClass("isRioter")?
newFlares(b,f,g,k,e,c,$this):Tags($this)})}};b.open("GET",z,!0);b.send()}
function newFlares(b,a,d,f,g,k,e){var c,h=e.attr("data-apollo-pvpnet-id");for(c=b.length-1;-1<c;--c)h===b[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cemissary'><a style='color:#fff' href='https://boards."+region+".leagueoflegends.com/en/c/announcements-en/91vEPc8g'>Senior Emissary</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle temissary'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #00aa00").end().attr("id",
"emissary");for(c=a.length-1;-1<c;--c)h===a[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cemissary'><a style='color:#fff' href='https://boards."+region+".leagueoflegends.com/en/c/announcements-en/91vEPc8g'>Emissary</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle temissary'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #00aa00").end().attr("id","emissary");
for(c=d.length-1;-1<c;--c)h===d[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cemissary'><a style='color:#fff' href='https://boards."+region+".leagueoflegends.com/en/c/announcements-en/91vEPc8g'>Junior Emissary</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle temissary'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #00aa00").end().attr("id","emissary");for(c=
f.length-1;-1<c;--c)h===f[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cwrenchman'><a style='color:#fff' href='https://boards.euw.leagueoflegends.com/en/c/announcements-en/gmQTWs7V'>Senior Wrenchman</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle twrenchman'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #ff5214").end().attr("id","wrenchman");for(c=g.length-
1;-1<c;--c)h===g[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cwrenchman'><a style='color:#fff' href='https://boards.euw.leagueoflegends.com/en/c/announcements-en/gmQTWs7V'>Wrenchman</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle twrenchman'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #ff5214").end().attr("id","wrenchman");for(c=k.length-1;-1<c;--c)h===
k[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cwrenchman'><a style='color:#fff' href='https://boards.euw.leagueoflegends.com/en/c/announcements-en/gmQTWs7V'>Junior Wrenchman</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle twrenchman'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #ff5214").end().attr("id","wrenchman")}
function Tags(b){var a=b.attr("href").split("/");z="https://boards."+region+".leagueoflegends.com/api/users/"+a[3]+"/"+a[4];a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var a=JSON.parse(this.responseText);null!==a.profile&&!0===a.profile.data.hasOwnProperty("title")&&(a=a.profile.data.title,b.parents(".byline:not(.discussion-footer)").append("<span class='tags crioter'>"+a+"</span>"))}};a.open("GET",z,!0);a.send()}
function commentParent(){if(0===$chronoView&&2>$boardIndex){var b=$("#discussion").find("li.view-in-mod-tool a").attr("href").split("/"),a=b[4],d=b[6];$(".nested-comment:not(.isChild):not(.isDeleted)").each(function(){this.className+=" isChild";var b=$(this).attr("id");if(void 0!==b&&b.length&&12<b.length){l=b.slice(8,-4);z="https://boards."+region+".leagueoflegends.com/api/"+a+"/discussions/"+d+"/comment/"+l+".json";var g=this;b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState&&
200===this.status){var a=JSON.parse(this.responseText),b=a.user.name,c=a.user.realm;a=a.message;$(g).find(".body").prepend("<p class='op-ref' style='display:none'>"+a+"</p>").end().find(".header.byline.clearfix").append("<span class='op-ref-bar'>In response to: <a href='https://boards."+region+".leagueoflegends.com/en/player/"+c+"/"+b+"'>"+b+"</a> ("+c+') (<a class=\'toggle-op noshow\' href=\'javascript:;\' onclick=\'$(this).hasClass("noshow") ? ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:block"), $(this).attr("class", "toggle-op yesshow"), $(this).text("hide")) : ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:none"), $(this).attr("class", "toggle-op noshow"), $(this).text("show"));\'>show</a>)</span>')}};
b.open("GET",z,!0);b.send();$(this).find(".controls").append('<li data-bind="visible"><a class="toggle-reply-form permalink" href="?show=flat&comment='+l+'">Go to Parent</a></li>')}})}}
function boardIndexFlares(){0<$boardIndex&&$(".discussion-list-item:not(.wr)").each(function(){this.className+=" wr";$this=$(this);discID=$this.attr("data-discussion-id");appID=$this.attr("data-application-id");z="https://apollo.na.leagueoflegends.com/apollo/applications/"+appID+"/discussions/"+discID+"?page_size=0";var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var a=JSON.parse(this.responseText);if(!0===a.discussion.content.hasOwnProperty("pinned")&&
!1===a.discussion.hasRioterComments){var b=a.discussion.content.pinned;a=a.discussion.id;"okOuNvuT"===appID?$this.find(".riot-commented").append("<a href='/en/c/ask-the-community/"+a+"?comment="+b+"' class='atc-fist opaque'>&nbsp;</a>"):"osqw6G4M"===appID?$this.find(".riot-commented").append("<a href='/en/c/help-support/"+a+"?comment="+b+"' class='poro-fist opaque'>&nbsp;</a>"):"6heBIhQc"===appID&&$this.find(".riot-commented").append("<a href='/en/c/community-moderation/"+a+"?comment="+b+"' class='dtb-fist opaque'>&nbsp;</a>")}}};
b.open("GET",z,!0);b.send()})}function flatScroll(){0!==$("#comments").find(".pager.clearfix").length&&$(".pager").children("a").click(function(){$("html,body").animate({scrollTop:$(".comments-header-container").offset().top},"slow")})}
function archived(){if(0===$boardIndex&&0!==$("#sidebar").find("div.new-discussion-box.box a").length&&-1!==$("#comments").find("span.cant-comment-warning").text().indexOf("Commenting is disabled")){var b=$("#sidebar").find("div.new-discussion-box.box a").attr("href");void 0!==b&&b.length&&-1<b.length&&$(".cant-comment-warning").html('<span class="icon-lock-brown"></span>This thread has been archived. <a href="'+b+'">Create a new thread instead?</a>')}};