$(function(){Cycle()});$(document).click(Cycle);var $boardIndex=$(".discussion-list-item").length,$chronoView=0,$subBoard=$("#breadcrumbs h2").text(),firstRun=1,pageURL=window.location.href,region=null,lang=null;function Cycle(){var b=setInterval(function(){firstRun=1;$chronoView=$("#comments").find(".list").length;var c=pageURL.split("/");region=pageURL.split(".")[1];lang=c[3];++firstRun;0<$boardIndex&&IndexVoting();commentParent()},500);setTimeout(function(){clearInterval(b)},2E3)}
function IndexVoting(){$("#discussion-list").find("td.voting:not(#cv):not(:has(.pin)):contains('                ')").attr("id","cv").html("<div class='locked'></div>").end().find("ul.upVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #009700").end().end().end().find("ul.downVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #e23636").end().end().end().find("button.up-vote").remove().end().find("button.down-vote").remove().end();for(var b=
$("#discussion-list").find(".riot-apollo.voting:not(.wx)"),c=0;c<b.length;++c){var a=b[c];a.className+=" wx";var d=$(a).attr("data-apollo-up-votes"),e=$(a).attr("data-apollo-down-votes");d-=e;1===d?$(a).find("ul.riot-voting").append("<li>Vote</li>").end().find(".total-votes").attr("style","color:#22b722"):0===d?$(a).find(".total-votes").attr("style","color:#13bbc1").end().find("ul.riot-voting").append("<li>Votes</li>"):0<d?$(a).find(".total-votes").attr("style","color:#22b722").end().find("ul.riot-voting").append("<li>Votes</li>"):
0>d&&$(a).find(".total-votes").attr("style","color:#fd3b3b").end().find("ul.riot-voting").append("<li>Votes</li>")}}
function Tags(){$("a.profile-hover:not(.ck)").each(function(){$this=$(this);this.className+=" ck";var b=$this.attr("href").split("/");z="https://boards.na.leagueoflegends.com/api/users/"+b[3]+"/"+b[4];var c=this;b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var a=JSON.parse(this.responseText);null!==a.profile&&!0===a.profile.data.hasOwnProperty("title")&&Titles(a.isRioter,a.profile.data.title,c)}};b.open("GET",z,!0);b.send()})}
function Titles(b,c,a){if(!0===b)$(a).parents(".byline:not(.discussion-footer)").append("<span class='tags crioter'>"+c+"</span>");else switch(c){case "Herald":$(a).parents(".byline:not(.discussion-footer)").append("<span class='tags cherald'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle therald'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style",
"border-top:1px solid #9c4ad9").end().attr("id","herald");break;case "Advisor":$(a).parents(".byline:not(.discussion-footer)").append("<span class='tags cadvisor'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tadvisor'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #87CEEB").end().attr("id",
"advisor");break;case "Moderator":$(a).parents(".byline:not(.discussion-footer)").append("<span class='tags cmoderator'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tmoderator'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #7fe4af").end().attr("id","moderator");break;case "NA Player Support":$(a).parents(".byline:not(.discussion-footer)").append("<span class='tags cnaps'>"+
c+"</span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tnaps'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #cc6600").end().attr("id","naps");break;case "Archivist":$(a).parents(".byline:not(.discussion-footer)").append("<span class='tags carchivist'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tarchivist'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style",
"border-top:1px solid #9ca200").end().attr("id","archivist")}}
function commentParent(){if(0===$chronoView&&2>$boardIndex){var b=$("#discussion").find("li.view-in-mod-tool a").attr("href").split("/"),c=b[4],a=b[6];$(".nested-comment:not(.isChild):not(.isDeleted)").each(function(){this.className+=" isChild";var b=$(this).attr("id");if(void 0!==b&&b.length&&12<b.length){l=b.slice(8,-4);z="https://boards."+region+".leagueoflegends.com/api/"+c+"/discussions/"+a+"/comment/"+l+".json";var e=this;b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState&&
200===this.status){var a=JSON.parse(this.responseText),b=a.user.name,c=a.user.realm;a=a.message;$(e).find(".body").prepend("<p class='op-ref' style='display:none'>"+a+"</p>").end().find(".header.byline.clearfix").append("<span class='op-ref-bar'>In response to: <a href='https://boards."+region+".leagueoflegends.com/"+lang+"/player/"+c+"/"+b+"'>"+b+"</a> ("+c+') (<a class=\'toggle-op noshow\' href=\'javascript:;\' onclick=\'$(this).hasClass("noshow") ? ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:block"), $(this).attr("class", "toggle-op yesshow"), $(this).text("hide")) : ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:none"), $(this).attr("class", "toggle-op noshow"), $(this).text("show"));\'>show</a>)</span>')}};
b.open("GET",z,!0);b.send();$(this).find(".controls").append('<li data-bind="visible"><a class="toggle-reply-form permalink" href="?show=flat&comment='+l+'">Go to Parent</a></li>')}})}}
function HelpSupport(){0<$boardIndex&&("Help & Support"==$subBoard||"Ask the Community"==$subBoard||"Discuss the Boards"==$subBoard||"Testing Area"==$subBoard)&&$(".discussion-list-item:not(.wr)").each(function(){this.className+=" wr";$this=$(this);discID=$this.attr("data-discussion-id");appID=$this.attr("data-application-id");z="https://boards.na.leagueoflegends.com/api/"+appID+"/discussions/"+discID+".json?page_size=0";var b=this,c=new XMLHttpRequest;c.onreadystatechange=function(){if(4==this.readyState&&
200===this.status){var a=JSON.parse(this.responseText);if(!0===a.discussion.content.hasOwnProperty("pinned")&&!1===a.discussion.hasRioterComments){var c=a.discussion.content.pinned;a=a.discussion.id;"okOuNvuT"===appID?$(b).find(".riot-commented").append("<a href='/en/c/ask-the-community/"+a+"?comment="+c+"' class='atc-fist opaque'>&nbsp;</a>"):"osqw6G4M"===appID?$(b).find(".riot-commented").append("<a href='/en/c/help-support/"+a+"?comment="+c+"' class='poro-fist opaque'>&nbsp;</a>"):"6heBIhQc"===
appID&&$(b).find(".riot-commented").append("<a href='/en/c/community-moderation/"+a+"?comment="+c+"' class='dtb-fist opaque'>&nbsp;</a>")}}};c.open("GET",z,!0);c.send()})}$(function(){0!==$("#comments").find(".pager.clearfix").length&&$(".pager").children("a").click(function(){$("html,body").animate({scrollTop:$(".comments-header-container").offset().top},"slow")})});