$(function(){Cycle();flatScroll();archived()});$(document).click(Cycle);var $boardIndex=$(".discussion-list-item").length,$chronoView=0,$subBoard=$("#breadcrumbs h2").text(),firstRun=1;function Cycle(){var a=setInterval(function(){firstRun=1;$chronoView=$("#comments").find(".list").length;++firstRun;0<$boardIndex&&(IndexVoting(),boardIndexFlares());newTags();commentParent()},750);setTimeout(function(){clearInterval(a)},4500)}
function IndexVoting(){$("#discussion-list").find("td.voting:not(#cv):not(:has(.pin)):contains('                ')").attr("id","cv").html("<div class='locked'></div>").end().find("ul.upVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #009700").end().end().end().find("ul.downVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #e23636").end().end().end().find("button.up-vote").remove().end().find("button.down-vote").remove().end();for(var a=
$("#discussion-list").find(".riot-apollo.voting:not(.wx)"),b=0;b<a.length;++b){var d=a[b];d.className+=" wx";$v=$(d);d=$v.attr("data-apollo-up-votes");var f=$v.attr("data-apollo-down-votes");d-=f;1===d?$v.find("ul.riot-voting").append("<li>Vote</li>").end().find(".total-votes").attr("style","color:#22b722"):0===d?$v.find(".total-votes").attr("style","color:#13bbc1").end().find("ul.riot-voting").append("<li>Votes</li>"):0<d?$v.find(".total-votes").attr("style","color:#22b722").end().find("ul.riot-voting").append("<li>Votes</li>"):
0>d&&$v.find(".total-votes").attr("style","color:#fd3b3b").end().find("ul.riot-voting").append("<li>Votes</li>")}}
function newTags(){z="https://boards.na.leagueoflegends.com/api/tn3qAbc8/discussions/R9ENc662?page_size=0";var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var b=JSON.parse(this.responseText).discussion.content.body_html.split(";"),a=b[1].split(","),f=b[3].split(","),g=b[5].split(","),e=b[7].split(","),c=b[9].split(",");$("a.profile-hover:not(.cka)").each(function(){$this=$(this);this.className+=" cka";!1===$this.parent().hasClass("isRioter")?newFlares(a,
f,g,e,c,$this):Tags($this)})}};a.open("GET",z,!0);a.send()}
function newFlares(a,b,d,f,g,e){var c,h=e.attr("data-apollo-pvpnet-id");for(c=a.length-1;-1<c;--c)h===a[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cherald'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>Herald</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle therald'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #9c4ad9").end().attr("id",
"herald");for(c=b.length-1;-1<c;--c)h===b[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cadvisor'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>Advisor</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tadvisor'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #87CEEB").end().attr("id","advisor");for(c=d.length-
1;-1<c;--c)h===d[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cmoderator'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>Moderator</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tmoderator'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #7fe4af").end().attr("id","moderator");for(c=f.length-1;-1<c;--c)h===
f[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags carchivist'><a style='color:#fff' href='https://boards.na.leagueoflegends.com/en/c/community-moderation/LZ0eNgrM'>Archivist</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tarchivist'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #9ca200").end().attr("id","archivist");for(c=g.length-1;-1<c;--c)h===g[c]&&e.parents(".byline:not(.discussion-footer)").append("<span class='tags cnaps'>NA Player Support</span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tnaps'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style",
"border-top:1px solid #cc6600").end().attr("id","naps")}
function Tags(a){var b=a.attr("href").split("/");z="https://boards.na.leagueoflegends.com/api/users/"+b[3]+"/"+b[4];b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var b=JSON.parse(this.responseText);null!==b.profile&&!0===b.profile.data.hasOwnProperty("title")&&(b=b.profile.data.title,a.parents(".byline:not(.discussion-footer)").append("<span class='tags crioter'>"+b+"</span>"))}};b.open("GET",z,!0);b.send()}
function commentParent(){if(0===$chronoView&&2>$boardIndex){var a=$("#discussion").find("li.view-in-mod-tool a").attr("href").split("/"),b=a[4],d=a[6];$(".nested-comment:not(.isChild):not(.isDeleted)").each(function(){this.className+=" isChild";var a=$(this).attr("id");if(void 0!==a&&a.length&&12<a.length){l=a.slice(8,-4);z="https://boards.na.leagueoflegends.com/api/"+b+"/discussions/"+d+"/comment/"+l+".json";var g=this;a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200===
this.status){var a=JSON.parse(this.responseText),b=a.user.name,d=a.user.realm;a=a.message;$(g).find(".body").prepend("<p class='op-ref' style='display:none'>"+a+"</p>").end().find(".header.byline.clearfix").append("<span class='op-ref-bar'>In response to: <a href='https://boards.na.leagueoflegends.com/en/player/"+d+"/"+b+"'>"+b+"</a> ("+d+') (<a class=\'toggle-op noshow\' href=\'javascript:;\' onclick=\'$(this).hasClass("noshow") ? ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:block"), $(this).attr("class", "toggle-op yesshow"), $(this).text("hide")) : ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:none"), $(this).attr("class", "toggle-op noshow"), $(this).text("show"));\'>show</a>)</span>')}};
a.open("GET",z,!0);a.send();$(this).find(".controls").append('<li data-bind="visible"><a class="toggle-reply-form permalink" href="?show=flat&comment='+l+'">Go to Parent</a></li>')}})}}
function boardIndexFlares(){0<$boardIndex&&("Help & Support"==$subBoard||"Ask the Community"==$subBoard||"Discuss the Boards"==$subBoard||"Testing Area"==$subBoard)&&$(".discussion-list-item:not(.wr)").each(function(){this.className+=" wr";$this=$(this);discID=$this.attr("data-discussion-id");appID=$this.attr("data-application-id");z="https://boards.na.leagueoflegends.com/api/"+appID+"/discussions/"+discID+".json?page_size=0";var a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&
200===this.status){var a=JSON.parse(this.responseText);if(!0===a.discussion.content.hasOwnProperty("pinned")&&!1===a.discussion.hasRioterComments){var d=a.discussion.content.pinned;a=a.discussion.id;"okOuNvuT"===appID?$this.find(".riot-commented").append("<a href='/en/c/ask-the-community/"+a+"?comment="+d+"' class='atc-fist opaque'>&nbsp;</a>"):"osqw6G4M"===appID?$this.find(".riot-commented").append("<a href='/en/c/help-support/"+a+"?comment="+d+"' class='poro-fist opaque'>&nbsp;</a>"):"6heBIhQc"===
appID&&$this.find(".riot-commented").append("<a href='/en/c/community-moderation/"+a+"?comment="+d+"' class='dtb-fist opaque'>&nbsp;</a>")}}};a.open("GET",z,!0);a.send()})}function flatScroll(){0!==$("#comments").find(".pager.clearfix").length&&$(".pager").children("a").click(function(){$("html,body").animate({scrollTop:$(".comments-header-container").offset().top},"slow")})}
function archived(){if(0===$boardIndex&&0!==$("#sidebar").find("div.new-discussion-box.box a").length&&-1!==$("#comments").find("span.cant-comment-warning").text().indexOf("Commenting is disabled")){var a=$("#sidebar").find("div.new-discussion-box.box a").attr("href");void 0!==a&&a.length&&-1<a.length&&$(".cant-comment-warning").html('<span class="icon-lock-brown"></span>This thread has been archived. <a href="'+a+'">Create a new thread instead?</a>')}};