$(function(){Cycle()});$(document).click(Cycle);var $boardIndex=$(".discussion-list-item").length,$chronoView=0,$subBoard=$("#breadcrumbs h2").text(),firstRun=1;function Cycle(){var a=setInterval(function(){firstRun=1;$chronoView=$("#comments").find(".list").length;++firstRun;0<$boardIndex&&(IndexVoting(),HelpSupport());Tags();commentParent()},500);setTimeout(function(){clearInterval(a)},2E3)}
function IndexVoting(){$("#discussion-list").find("td.voting:not(#cv):not(:has(.pin)):contains('                ')").attr("id","cv").html("<div class='locked'></div>").end().find("ul.upVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #009700").end().end().end().find("ul.downVoted:not(#cv)").attr("id","cv").parent().parent().css("border-left","2px solid #e23636").end().end().end().find("button.up-vote").remove().end().find("button.down-vote").remove().end();for(var a=
$("#discussion-list").find(".riot-apollo.voting:not(.wx)"),c=0;c<a.length;++c){var b=a[c];b.className+=" wx";var d=$(b).attr("data-apollo-up-votes"),e=$(b).attr("data-apollo-down-votes");d-=e;1===d?$(b).find("ul.riot-voting").append("<li>Vote</li>").end().find(".total-votes").attr("style","color:#22b722"):0===d?$(b).find(".total-votes").attr("style","color:#13bbc1").end().find("ul.riot-voting").append("<li>Votes</li>"):0<d?$(b).find(".total-votes").attr("style","color:#22b722").end().find("ul.riot-voting").append("<li>Votes</li>"):
0>d&&$(b).find(".total-votes").attr("style","color:#fd3b3b").end().find("ul.riot-voting").append("<li>Votes</li>")}}
function Tags(){$("a.profile-hover:not(.ck)").each(function(){$this=$(this);this.className+=" ck";var a=$this.attr("href").split("/");z="https://boards.oce.leagueoflegends.com/api/users/"+a[3]+"/"+a[4];var c=this;a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var b=JSON.parse(this.responseText);null!==b.profile&&!0===b.profile.data.hasOwnProperty("title")&&Titles(b.isRioter,b.profile.data.title,c)}};a.open("GET",z,!0);a.send()})}
function Titles(a,c,b){if(!0===a)$(b).parents(".byline:not(.discussion-footer)").append("<span class='tags crioter'>"+c+"</span>");else switch(c){case "Emissary":$(b).parents(".byline:not(.discussion-footer)").append("<span class='tags cemissary'><a style='color:#fff' href='https://boards.oce.leagueoflegends.com/en/c/player-behaviour/Edu7E6Bp'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle temissary'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style",
"border-top:1px solid #458b00").end().attr("id","emissary");break;case "Wrenchman":$(b).parents(".byline:not(.discussion-footer)").append("<span class='tags cwrenchman'><a style='color:#fff' href='https://boards.oce.leagueoflegends.com/en/c/help-support-oce/nE4lj5EB'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle twrenchman'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #c98f1a").end().attr("id",
"wrenchman");break;case "Instructor":$(b).parents(".byline:not(.discussion-footer)").append("<span class='tags cinstructor'><a style='color:#fff' href='https://boards.oce.leagueoflegends.com/en/c/gameplay-strategy/RaWrI4Hi'>"+c+"</a></span>").end().closest(".nested-comment").find(".masthead:first").append("<span class='ttriangle tinstructor'></span>").end().end().closest(".nested-comment:not(.glow):not(.flat)").attr("style","border-top:1px solid #5079c4").end().attr("id","instructor")}}
function commentParent(){if(0===$chronoView&&2>$boardIndex){var a=$("#discussion").find("li.view-in-mod-tool a").attr("href").split("/"),c=a[4],b=a[6];$(".nested-comment:not(.isChild):not(.isDeleted)").each(function(){this.className+=" isChild";var a=$(this).attr("id");if(void 0!==a&&a.length&&12<a.length){l=a.slice(8,-4);z="https://boards.oce.leagueoflegends.com/api/"+c+"/discussions/"+b+"/comment/"+l+".json";var e=this;a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&
200===this.status){var a=JSON.parse(this.responseText),b=a.user.name,c=a.user.realm;a=a.message;$(e).find(".body").prepend("<p class='op-ref' style='display:none'>"+a+"</p>").end().find(".header.byline.clearfix").append("<span class='op-ref-bar'>In response to: <a href='https://boards.oce.leagueoflegends.com/en/player/"+c+"/"+b+"'>"+b+"</a> ("+c+') (<a class=\'toggle-op noshow\' href=\'javascript:;\' onclick=\'$(this).hasClass("noshow") ? ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:block"), $(this).attr("class", "toggle-op yesshow"), $(this).text("hide")) : ($(this).parent().parent().parent().find(".op-ref").attr("style", "display:none"), $(this).attr("class", "toggle-op noshow"), $(this).text("show"));\'>show</a>)</span>')}};
a.open("GET",z,!0);a.send();$(this).find(".controls").append('<li data-bind="visible"><a class="toggle-reply-form permalink" href="?show=flat&comment='+l+'">Go to Parent</a></li>')}})}}
function HelpSupport(){0<$boardIndex&&("Help & Support (OCE)"==$subBoard||"Testing Board"==$subBoard)&&$(".discussion-list-item:not(.wr)").each(function(){this.className+=" wr";$this=$(this);discID=$this.attr("data-discussion-id");appID=$this.attr("data-application-id");z="https://boards.oce.leagueoflegends.com/api/"+appID+"/discussions/"+discID+".json?page_size=0";var a=this,c=new XMLHttpRequest;c.onreadystatechange=function(){if(4==this.readyState&&200===this.status){var b=JSON.parse(this.responseText);
if(!0===b.discussion.content.hasOwnProperty("pinned")&&!1===b.discussion.hasRioterComments){var c=b.discussion.content.pinned;b=b.discussion.id;"ElA0rvVL"===appID&&$(a).find(".riot-commented").append("<a href='/en/c/help-support-oce/"+b+"?comment="+c+"' class='wrench-fist opaque'>&nbsp;</a>")}}};c.open("GET",z,!0);c.send()})}
$(function(){0!==$("#comments").find(".pager.clearfix").length&&$(".pager").children("a").click(function(){$("html,body").animate({scrollTop:$(".comments-header-container").offset().top},"slow")})});
$(function(){if(0===$boardIndex&&0!==$("#sidebar").find("div.new-discussion-box.box a").length&&-1!==$("#comments").find("span.cant-comment-warning").text().indexOf("Commenting is disabled")){var a=$("#sidebar").find("div.new-discussion-box.box a").attr("href");void 0!==a&&a.length&&-1<a.length&&$(".cant-comment-warning").html('<span class="icon-lock-brown"></span>This thread has been archived. <a href="'+a+'">Create a new thread instead?</a>')}});